Repository Shivang2003/DSA-Problems, pull requests merged in 2022-10, with the labels that each got.

#3 Create Circular Linked list primitive operations.c
  Circular Linked list primitive operations.c
Labels: Hacktoberfest-Accepted

#7 Added String programs and organized the files
  ARRAY Problems/ArrayDeletion.c
  ARRAY Problems/ArrayInsertion.c
  ARRAY Problems/ArrayTraversal.c
  LINKED LIST Problems/Circular Linked list primitive operations.c
  LINKED LIST Problems/Double Linked List Primitive operations.c
  LINKED LIST Problems/LLInsertFirstNode.c
  String Problems/LengthOfString.c
  String Problems/LengthOfString2.c
  String Problems/StringPalindrome.c
  String Problems/StringRev.c
  String Problems/StringRev2.c
Labels: hactoberfest, Hacktoberfest-Accepted

#9 Added program for stacks
  Stacks/primitive operations in stack.c
Labels: question, hactoberfest, Hacktoberfest-Accepted

#11 singly Linked List primitive operation
  Singly Linked List/Singly-LL.c
  Singly Linked List/Singly-LL.exe
Labels: hactoberfest, Hacktoberfest-Accepted
